version: 2
updates:
  - package-ecosystem: pip
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: [felippecaso]
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    reviewers: [felippecaso]
    commit-message:
      prefix: "ci: "
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers: [felippecaso]
    commit-message:
      prefix: "ci: "
